[package]
name = "stats_gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.7.2"
log = "0.4.17"
fraction = "0.13.0"
num-traits = "0.2.15"
pretty_env_logger = "0.4.0"
wavelet_rs = { path = "../../" }
clap = { version = "4.1.6", features = ["derive"] }
serde = { version = "1.0.152", features = ["derive"] }
rand = { version = "0.8.5", features = ["small_rng"] }